/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

#include <stdio.h>

int fib(int limit) {
    int x = 1;
    int y = 2;
    int z = 0;
    int evenSum = 0;

    while (y < limit) {
        if (y % 2 == 0) {
            evenSum = evenSum + y;
        }
        z = x + y;
        x = y;
        y = z;
    }
    return evenSum;
}

int main () {

    printf("%d\n", fib(4000000));

    return 0;
}
